--- #YAML:1.0
name: Catalyst-Plugin-Cache-Memcached
version: 0.6
author:
  - Christian Hansen, C<ch@ngmedia.com>
Sebastian Riedel C<sri@oook.de>
abstract: Distributed cache
license: perl
generated_by: Module::Build version 0.2612, without YAML.pm
